language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install:
  - git clone --recurse-submodules  https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT